name: publish
on: [push]
jobs:
  publish-trex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Trex Docker image
        run: |
          docker build . --tag ghcr.io/turnos/trex:latest
          docker push ghcr.io/turnos/trex:latest


